settings:
  name: BlueXP remediation
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP remediation docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP remediation
          url: /concept-resource-templates.html
        - title: Learn about tagging
          url: /concept-tagging.html
    - title: Use BlueXP remediation
      entries:
        - title: Use templates to standardize resource creation
          entries:
            - title: Build templates for your organization
              url: /task-define-templates.html
            - title: Check resources for template compliance
              url: /task-check-template-compliance.html
            - title: Run templates to create resources
              url: /task-run-templates.html
        - title: Organize your resources using tags
          entries:
            - title: Manage tags for your resources
              url: /task-using-tags.html
    - title: Concepts
      entries:
        - title: Template building blocks
          url: /reference-template-building-blocks.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about BlueXP remediation
          url: concept-resource-templates.html
        - title: Learn about Tagging
          url: concept-tagging.html
        - title: What's New
          url: whats-new.html
    - title: Create templates
      links:
        - title: Cloud Volumes ONTAP working environment
          url: task-define-templates.html#create-a-template-for-a-cloud-volumes-ontap-working-environment
        - title: Cloud Volumes ONTAP volume
          url: task-define-templates.html#create-a-template-for-a-cloud-volumes-ontap-volume
        - title: Azure NetApp Files volume
          url: task-define-templates.html#create-a-template-for-an-azure-netapp-files-volume
        - title: On-premises ONTAP volume
          url: task-define-templates.html#create-a-template-for-an-on-premises-ontap-volume
        - title: Add Backup, Classification, or Replication functionality to a volume
          url: task-define-templates.html#examples-of-enabling-services-using-templates
    - title: Create resources using templates
      links:
        - title: Cloud Volumes ONTAP working environment
          url: task-run-templates.html#select-and-run-a-working-environment-template
        - title: Volume for CVO, on-prem, and ANF
          url: task-run-templates.html#select-and-run-a-volume-template
    - title: Manage resources using templates and tags
      links:
        - title: Check resources for template compliance (drift)
          url: task-check-template-compliance.html
        - title: Run a template that finds existing resources
          url: task-run-templates.html#select-and-run-a-template-that-finds-existing-resources
        - title: Manage tags for your resources
          url: task-using-tags.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/BlueXP-and-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://bluexp.netapp.com/blog
        - title: Cloud webinars
          url: https://bluexp.netapp.com/events
