---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes
summary: Learn what's new in BlueXP remediation and Tagging.
---

= What's new with BlueXP remediation and Tagging
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn what's new in BlueXP remediation and Tagging.

// tag::whats-new[]
== 3 March 2022

=== Now you can build a Template to find specific working environments

Using the "Find Existing Resources" action you can identify the working environment, and then use other template actions, such as creating a volume, to easily perform actions on existing working environments. https://docs.netapp.com/us-en/bluexp-remediation/task-define-templates.html#examples-of-finding-existing-resources-and-enabling-services-using-templates[Go here for details].

=== Ability to create a Cloud Volumes ONTAP HA working environment in AWS

The existing support for creating a Cloud Volumes ONTAP working environment in AWS has been expanded to include creating a high-availability system in addition to a single-node system. https://docs.netapp.com/us-en/bluexp-remediation/task-define-templates.html#create-a-template-for-a-cloud-volumes-ontap-working-environment[See how to create a template for a Cloud Volumes ONTAP working environment].

== 9 February 2022

=== Now you can build a Template to find specific existing volumes and then enable Cloud Backup

Using the new "Find Resource" action you can identify all the volumes on which you want to enable Cloud Backup, and then use the Cloud Backup action to enable backup on those volumes.

Current support is for volumes on Cloud Volumes ONTAP and on-premises ONTAP systems. https://docs.netapp.com/us-en/bluexp-remediation/task-define-templates.html#find-existing-volumes-and-activate-bluexp-backup-and-recovery[Go here for details].

== 31 October 2021

=== Now you can tag your Sync relationships so you can group or categorize them for easy access

https://docs.netapp.com/us-en/bluexp-remediation/concept-tagging.html[Learn more about resource tagging].
// end::whats-new[]
